services:
  - type: web
    name: forex-data-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8080
    autoDeploy: true
    plan: free 
