services:
  - type: web
    name: forex-data-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.wsgi:app
    autoDeploy: true
    plan: free 
